### ISSUE TITLE
An error occurred: Cannot read properties of null (reading 'textContent')

### ISSUE THREAD

**Issue by d-taborda** [XternA/honeygain-pot#1]
Hello,

I have an issue with the honeygain-pot docker, running as part of igm. When checking the logs of honeygain-pot I can see the following error: 
**An error occurred: Cannot read properties of null (reading 'textContent')**

The main honeygain docker is working fine, but the auto claim of the pot via the honeygain-pot instance is not working.
I have attached a screenshot of the error I can see for more details.

Do you have any idea on what could the the issue?
Thank you.

![image](https://github.com/user-attachments/assets/3aa82dce-9665-4704-a2c9-f4787bfe1a4f)

**Comment by d-taborda** [comment]
Hello,

I'm running Ubuntu 24.04 LTS (GNU/Linux 6.8.0-40-generic x86_64).
My system is up to date, I've still tried to reboot to apply a few pendings packages and removed apps/reinstall and run in igm, but I get the same error. 
Yes I can login on Honeygain and see my device as active, there are no issues on that part. The main docker for honeygain is working well.

**Comment by XternA** [comment]
OK so standard x86 Linux, therefore it should work. I've tested even on a Ubuntu version and it's fine.

Anyways, I might know what the problem is and I've already pushed a new image update with the changes. See if that works. 

Kindly remove and redeploy again, which should force to pull the latest version that's already available.

Thanks.

**Comment by d-taborda** [comment]
Hello,

Yes i'm using Honeygain not JumpTask.
I've redeployed and it seems to connect fine for now, thank you for the prompt help!
I will monitor in the next few days and update you again in case there is still an issue, but it seems resolved for now.
![image](https://github.com/user-attachments/assets/27ab40a7-a8d2-4f05-8029-51dba1192705)

**Comment by XternA** [comment]
If it's showing fine now then I can confidently confirm that there won't be any issues and it will continue to work for you now.

All the answers I've gathered basically has proven my theory behind why it didn't work.

**Comment by d-taborda** [comment]
Hello,

After your changes it was working fine, but recently I redeployed the apps (after a few updates from your tool) and it seems that the honeygain-pot is not working anymore since then. Not sure if it is related to the recent changes.

This is the error I see in the logs, even after restart of the apps:
![Screenshot 2024-09-02 233655](https://github.com/user-attachments/assets/d468a939-3fd5-4c7b-8755-01b4b9f7e20f)

**Comment by XternA** [comment]
Hello, 

Just to clarify, any changes to the IGM tool has no direct correlation or affects the Honeygain Pot component. They're completely separate from the changes.

Anyways I don't seem to have the issues you're facing, however there was a small change that happened to the site which I got affected from after I saw your ticket comment (remaining timer counter).

I've updated the docker image already and all the dependencies within the script, alongside a quick fix to the remaining timer countdown for the next claim that I 've discovered.

A new version of the docker image has been pushed already. Please go ahead and redeploy so that the new version can be pulled. Let's see if it will just fix the issue you've had.

**Comment by d-taborda** [comment]
Thanks for your help.
I've redeployed the apps after checking your message, but I still see some errors in the logs on my end as follows:
![image](https://github.com/user-attachments/assets/4f22b84a-cfd3-44a3-93e6-3c4d267a745f)

**Comment by XternA** [comment]
I can't reproduce your error at all so it's very hard for me to look into the problem. But it seems like only you're getting this issue.

The most I get is one of these:

![image](https://github.com/user-attachments/assets/970212f0-a3fd-4537-9017-d7fa72862f6f)

Which is very normal because sometimes we have to acknowledge that the bot can't access the site or network problems. Normally a restart of the Honeygain-pot container does the job for me...

I've made some other changes anyways but let's try this again.

Can you do the following:

1. Stop the applications.
2. Update your system.
3. Use the IGM tool and try to increase the resource limit, I would say set it to `max` for now just to see if it's to do with the constraints causing the browser to fail navigating the site.
4. Redeploy again.

Additionally, can you also check afterwards by going into the Honeygain container and ping to see if it can actually reach the Honeygain website.

```sh
docker exec -it honeygain-pot sh
```
This will take you inside the Honeygain shell, then execute:
```sh
ping dashboard.honeygain.com
```
If your output looks like mine then it means the container is able to reach Honeygain endpoint.
![image](https://github.com/user-attachments/assets/d65e9adf-6ca3-425c-aba8-fe85be1a5c35)
Exit out the container by typing `exit` command.

Finally, can I just get a sense of your Linux machine's hardware.

1. CPU cores?
2. Total RAM installed?

If all this doesn't work, please stop honeygain from this machine, try and deploy it onto another machine just to see if another machine doesn't end up with the same problem.

This is all I can think of now but thanks for your patience.

**Comment by d-taborda** [comment]
I am usually set to MAX, but it might be because I lowered the specs of my VM (1vCPU/1GB RAM), i've put it back to 2/2 and it seems fine now..
Thanks for your help on this, much appreciated.

**Comment by XternA** [comment]
Ah, thanks for sharing that. That would make sense why you were always getting the issue.

Yes, please refrain from setting your VM low config. With that said I think the system is exhausting from the rest of the resources and hence it's too slow for the bot to run.

Despite the bot being low resource utilisation, it does have to boot up a browser which will require quite a bit of resources in order to run properly, connect to the site, claim and disconnect. And sharing all that 1GB resource with 1vCore with other Linux system processes will cause the browser to halt.

Glad it's resolved now. Also a good information for anyone in the future who's also spec a lower VM.
